### PR TITLE
Add additional retries to the index reload

### PR DESCRIPTION
**Pull request by maartenba**
@skofman1 @xavierdecoster @yishaigalatzer

### CODE REVIEW

**Comment by xavierdecoster** [comment]
:ship:

**Comment by skofman1** [comment]
Why? Is there a related issue?

**Comment by maartenba** [comment]
Last week we had a case where index was too Big to load smoothly. Additional attempts to load would have been cool.

**Comment by ryuyu** [comment]
Are the maxRetries in both locations supposed to be shared, or separate is okay?

LGTM

**Comment by scottbommarito** [comment]
Any reason this hasn't been merged yet?

**Pull request merged**
