### PR TITLE
Hotfix binding redirects for search services

### PR DESCRIPTION
**Pull request by xavierdecoster**
Cherry-picked the changes from `master` and resolved merge conflicts in separate branch.
Supersedes https://github.com/NuGet/NuGet.Services.Metadata/pull/538

### CODE REVIEW

**Comment by joelverhagen** [comment]
Is this a merge or a cherry-pick? Typically we do a git merge so that future `dev` to `master` merges know that the hotfix commit is already on master.

**Comment by xavierdecoster** [comment]
Noticed build of `dev` branch is failing due to unit test failures. Have a PR open [here](https://github.com/NuGet/NuGet.Services.Metadata/pull/540).

**Comment by xavierdecoster** [comment]
> Is this a merge or a cherry-pick? Typically we do a git merge so that future `dev` to `master` merges know that the hotfix commit is already on master.

It's a cherry-pick with a manual resolution of merge conflicts. There's another commit on `dev` that updates assembly binding redirects...

**Comment by xavierdecoster** [comment]
@joelverhagen simulated `dev` to `master`: zero merge conflicts.

**Pull request merged**
