### PR TITLE
In progress - Improve catalog to registration performance

### PR DESCRIPTION
**Pull request by joelverhagen**
1. Don't read the leaf nodes of the registration, only reading the index.json (and pages on large registration) is necessary.
2. Only write new registration leaf blobs. With this change, the new (that is added or updated) leaf nodes are updates along with the page and index.json blobs.

### CODE REVIEW

**Comment by maartenba** [comment]
@joelverhagen What's the status on this one?

**Comment by joelverhagen** [comment]
I verified the fix manually, but the `searchcloud` branch has moved forward significantly since then so the code should be verified again. Essentially, I ensured that the registration blobs generated from the catalog for a big package (e.g. `Catel.MVVM`) are the equivalent before and after my change.

@johnataylor, you looked at this code as well, right?

**Comment by maartenba** [comment]
Going to close this one in favor of https://github.com/NuGet/NuGet.Services.Metadata/pull/59

**Comment by joelverhagen** [comment]
Thanks for taking care of this.

**Pull request closed without merging**
