### PR TITLE
Camel case includes numbers

### PR DESCRIPTION
**Pull request by yishaigalatzer**

### CODE REVIEW

**Comment by yishaigalatzer** [comment]
This is a theoretical change, the tests all pass, but I assume we will need to reindex to see a difference 
CC @maartenba @joelverhagen @xavierdecoster @harikm86

**Comment by maartenba** [comment]
Theoretical change looks good. When flighting the new search, should I include this change?

**Comment by yishaigalatzer** [comment]
Let's take this one through dev first?

**Comment by maartenba** [comment]
Superseded by https://github.com/NuGet/NuGet.Services.Metadata/pull/71
(use branch `wip/camelcasenumbers`)

**Pull request closed without merging**
