### PR TITLE
Add job name to trace properties in AI

### PR DESCRIPTION
**Pull request by skofman1**
@maartenba @xavierdecoster @shishirx34 @ryuyu @scottbommarito 

Also updated NuGet.Services.Logging to the latest version of AI sink, and now it supports sending logs as AI Traces, meaning we will get a nice view AI Search window (especially for you @scottbommarito ;))

### CODE REVIEW

**Comment by scottbommarito** [comment]
Awesome!

10/10 LGTM

**Comment by ryuyu** [comment]
:shipit:

**Comment by maartenba** [comment]
Dependency galore 😀

LGTM

**Comment by xavierdecoster** [comment]
LGTM. Whilst at it, would it be possible to also update to v1.0.0 of the MS.Extentions.Logging dependencies?

**Comment by shishirx34** [comment]
LGTM

**Comment by skofman1** [comment]
Merged

**Pull request closed without merging**
