### PR TITLE
Enable CORS for API v3

### PR DESCRIPTION
**Pull request by maartenba**
See https://github.com/NuGet/NuGetGallery/issues/3037

/cc @skofman1 @xavierdecoster @blowdart

### CODE REVIEW

**Comment by skofman1** [comment]
I trust you :)

**Comment by blowdart** [comment]
I don't, but it looks fine :D

**Comment by maartenba** [comment]
Thanks!

**Comment by rappen** [comment]
@maartenba I'm the one thanking :+1: 
So I guess it is in ``dev`` now, any idea when it will be public?

**Comment by maartenba** [comment]
@rappen Somewhere in the next week, currently validating our CDN has proper support as well.

**Pull request merged**
