### PR TITLE
[ReleasePrep][2020.01.23]RI of dev into master

### PR DESCRIPTION
**Pull request by loic-sharma**

### CODE REVIEW

**Comment by joelverhagen** [comment]
Should we wait for https://github.com/NuGet/NuGet.Services.Metadata/pull/732, @xavierdecoster?

**Comment by xavierdecoster** [comment]
> Should we wait for #732, @xavierdecoster?

Preferably, I'm running final validations on that PR. Aiming to merge by EOD.

**Comment by loic-sharma** [comment]
@xavierdecoster I see https://github.com/NuGet/NuGet.Services.Metadata/pull/732 is done, were you able to test this on dev?

**Comment by xavierdecoster** [comment]
@loic-sharma Where are we tracking the deployments that we'll do when this PR hits `master`?

**Comment by xavierdecoster** [comment]
> @xavierdecoster I see #732 is done, were you able to test this on DEV?

Yes

**Comment by loic-sharma** [comment]
> @loic-sharma Where are we tracking the deployments that we'll do when this PR hits `master`?

I created a deployment work item here: https://github.com/NuGet/NuGetGallery/issues/7821. FYI, I plan to deploy Azure Search myself, so I didn't add it to the deployment work item.

**Comment by xavierdecoster** [comment]
FYI, [this issue](https://github.com/nuget/engineering/issues/2950) describes all the jobs affected by this PR that need to be deployed once merged. Would be great if we can fan out some of these deployments 😄

**Comment by loic-sharma** [comment]
> Would be great if we can fan out some of these deployments 😄

If you'd like you can put some (or all) of these deployments on the on-call engineer

**Pull request merged**
